### PR TITLE
The default MPL OS X backend generates an assert on OS X, so explicit…

### PR DESCRIPTION
**Pull request by kollivier**
…ly choose the PostScript backend there. Add a test that uses MPL to ensure the fix works on OS X (and elsewhere).

Note that I committed a small audio file to test the function with, and made a note about the source / license (public domain) of the file.

### CODE REVIEW

**Comment by ivanistheone** [comment]
Trying this now using this file https://archive.org/download/WilhelmScreamSample/WilhelmScream.mp3

In Python 3 there was an error
```
>           subsignals = signal[(length-count)/2 : (length+count)/2]
E           TypeError: slice indices must be integers or None or have an __index__ method
```
(seems to assume Py2.7 semantics of int/int = int; I'll try to fix)


In Python 2.7 tests pass but there is a warning:
```
warnings summary
tests/test_thumbnails.py::Test_wavefile_thumbnail_generation::()::test_generates_thumbnail
  /Users/ivan/Projects/FLECode/pressurecooker/venv2/lib/python2.7/site-packages/matplotlib/transforms.py:2786: RuntimeWarning: overflow encountered in short_scalars
    elif vmax - vmin <= maxabsvalue * tiny:
```

will continue to play with it see if I can fix

**Comment by ivanistheone** [comment]
Ran into another issue, 
```
>               if not np.all(xravel.mask):
E               AttributeError: 'numpy.ndarray' object has no attribute 'mask'
venv/lib/python3.6/site-packages/matplotlib/units.py:169: AttributeError
self = <tests.test_thumbnails.Test_wavefile_thumbnail_generation object at 0x10d4ce588>
    def test_generates_thumbnail(self, tmpdir):
>       images.create_waveform_image(input_file, output_file, 
in tests/test_thumbnails.py:25:
...
    def safe_first_element(obj):
        if isinstance(obj, collections.Iterator):
            try:
                return obj[0]
>           raise RuntimeError("matplotlib does not support generators "
                               "as input")
E           RuntimeError: matplotlib does not support generators as input
```
which seems to be caused by the call to 

    ax.plot(zip(np.arange(count), subsignals), color)

after changing to 

    ax.plot(np.arange(count), subsignals, color)

it started working

**Comment by ivanistheone** [comment]
@kollivier Pleas check the two new commits I added. Tests pass now, but there is still the overflow warning printed if you run with `pytest -s` (no capture):

```
tests/test_thumbnails.py::Test_wavefile_thumbnail_generation::()::test_generates_thumbnail
  /Users/ivan/Projects/FLECode/pressurecooker/venv/lib/python3.6/site-packages/matplotlib/transforms.py:2786: RuntimeWarning: overflow encountered in short_scalars
    elif vmax - vmin <= maxabsvalue * tiny:
```

I think would be OK to merge since generated thumb looks good.

**Comment by kollivier** [comment]
@ivanistheone The changes look good to me! Thanks for catching those! :)

**Comment by ivanistheone** [comment]
New version is now on PyPI: https://pypi.org/project/pressurecooker/

**Pull request merged**
